<a href="https://colab.research.google.com/github/mustafabozkaya/Deep_Learning_Bootcamp/blob/master/5_Weeks_of_Deep_Learning_week0_Quize1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Select the correct statement(s) about Tensors. (There can be multiple correct answers, please select all of them)



We cannot change the content of a Tensor like strings or numbers in Python


Tensors are immutable





2.Select the correct option
A Tensor is a multidimensional array and can have elements of two or more different data types.



True


False**

In [2]:
import tensorflow as tf
tensor=tf.constant([

           [[0, 1, 2, 3, 4],

            [5, 6, 7, 8, 9]],

           [[10, 11, 12, 13, 14],

            [15, 16, 17, 18, 19]],

           [[20, 21, 22, 23, 24],

            [25, 26, 27, 28, 29]],])

In [17]:
t[0][1][2]=5 # tensor is immutable like numpy

TypeError: ignored

In [3]:
tensor.ndim

3

In [7]:
tensor.shape

TensorShape([3, 2, 5])

In [8]:
tensor = tf.constant([2, 14, 10, 12, 15, 3, 2, 5, 15, 78])

In [9]:
tensor[1]

<tf.Tensor: shape=(), dtype=int32, numpy=14>

In [10]:
tensor[-1]

<tf.Tensor: shape=(), dtype=int32, numpy=78>

In [11]:
tensor[:5]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 2, 14, 10, 12, 15], dtype=int32)>

In [12]:
tensor[::2]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 2, 10, 15,  2, 15], dtype=int32)>

In [13]:
t = [

[3, 2, 1],

[6, 5, 4],

[9, 8, 7]

]

In [14]:
t[1][0]

6

In [15]:
t = tf.constant([

    [

         [2, 4, 4, 3] 

        ,[3, 2, 4, 5]

    ]

])
t.shape

TensorShape([1, 2, 4])